language: ruby
rvm:
  - 2.4.1

script: bash ./deploy.sh

branches:
  only:
  - master
  - develop

env:
  global:
  - ENCRYPTION_LABEL: "5453d0fdf68a"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"

sudo: false

cache: bundler
