# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
url:            "https://bootstrap-table.wenzhixin.net.cn"
encoding:       UTF-8

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Custom variables
current_version:  1.13.1
title:            "Bootstrap Table"
description:      "An extended Bootstrap table with radio, checkbox, sort, pagination, and other added features."
repo:             https://github.com/wenzhixin/bootstrap-table
website:          http://wenzhixin.net.cn
repos:            http://repos.wenzhixin.net.cn
email:            wenzhixin2010@gmail.com
master_zip:       https://github.com/wenzhixin/bootstrap-table/archive/master.zip

toc:
  min_level:      2
  max_level:      4
