# Dependencies
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - tables
  - autolink
highlighter: rouge

# Permalinks
permalink: pretty

# Languages
languages: ["en", "zh-cn", "fr"]
languages_string: ["English", "Chinese", "French"]

# Custom vars
current_version: 1.5.0
repo: https://github.com/wenzhixin/bootstrap-table
website: http://wenzhixin.net.cn
repos: http://repos.wenzhixin.net.cn
email: wenzhixin2010@gmail.com
master_zip: https://github.com/wenzhixin/bootstrap-table/archive/master.zip